export const bureaucratConstants = {
	BUREAUCRAT_LIST_REQUEST:0, 
	BUREAUCRAT_LIST_SUCCESS: 1, 
	BUREAUCRAT_LIST_FAIL: 2, 
	BUREAUCRAT_DETAILS_REQUEST: 3, 
	BUREAUCRAT_DETAILS_SUCCESS: 4, 
	BUREAUCRAT_DETAILS_FAIL: 5
}